version: '3'
services:
  app:
    container_name: app
    build: .
    ports:
      - 5000:4002
    depends_on:
      - db
      - cache
    volumes:
      - .:/app
  db:
    image: postgres:13
    container_name: db
    ports:
      - 2345:5432
    env_file:
      - .env
    restart: always
    volumes:
      - postgres:/var/lib/postgres/data
  cache:
    image: redis:6.2-alpine
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    container_name: cache
    ports:
      - 6379:6379
    restart: always
    volumes:
      - cache:/data
volumes:
  postgres:
    driver: local
  cache:
    driver: local
