version: '3'
services:
  app:
    container_name: app
    build: .
    ports:
      - 5000:4002
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
  db:
    image: postgres:13
    container_name: db
    ports:
      - 2345:5432
    env_file:
      - .env
    restart: always
    volumes:
      - postgres:/var/lib/postgres/data
  redis:
    image: redis:6.2-alpine
    command: redis-server
    container_name: redis
volumes:
  postgres:
